import type { PolicyRule } from './types';

export const STARTER_RULES: PolicyRule[] = [
  {
    ruleCode: 'DTI_MAX',
    ruleLabel: 'Debt-to-Income Maximum',
    category: 'INCOME',
    operator: 'LTE',
    thresholdValue: 0.43,
    thresholdHigh: null,
    allowedValues: null,
    factField: 'DTI_Ratio__c',
    severity: 'HARD_DECLINE',
    ruleExplanation: 'Your debt-to-income ratio exceeds our current threshold of 43%.',
    regulatoryCitation: 'CFPB 12 CFR 1026.43(c)(2)',
    versionNumber: 1,
    isActive: true,
  },
  {
    ruleCode: 'FICO_MIN',
    ruleLabel: 'Minimum FICO Score',
    category: 'CREDIT',
    operator: 'GTE',
    thresholdValue: 620,
    thresholdHigh: null,
    allowedValues: null,
    factField: 'FICO_Score__c',
    severity: 'HARD_DECLINE',
    ruleExplanation: 'Your credit score does not meet the minimum requirement of 620.',
    regulatoryCitation: 'FNMA B3-5.1-01',
    versionNumber: 1,
    isActive: true,
  },
  {
    ruleCode: 'LTV_CONVENTIONAL',
    ruleLabel: 'Loan-to-Value Maximum (Conventional)',
    category: 'COLLATERAL',
    operator: 'LTE',
    thresholdValue: 0.97,
    thresholdHigh: null,
    allowedValues: null,
    factField: 'LTV_Ratio__c',
    severity: 'SOFT_DECLINE',
    ruleExplanation: 'The loan-to-value ratio exceeds the maximum of 97% for conventional loans.',
    regulatoryCitation: 'FNMA B2-1.2-01',
    versionNumber: 1,
    isActive: true,
  },
  {
    ruleCode: 'INCOME_MIN',
    ruleLabel: 'Minimum Annual Income',
    category: 'INCOME',
    operator: 'GTE',
    thresholdValue: 25000,
    thresholdHigh: null,
    allowedValues: null,
    factField: 'Annual_Income__c',
    severity: 'SOFT_DECLINE',
    ruleExplanation: 'Annual income does not meet the minimum threshold of $25,000.',
    regulatoryCitation: null,
    versionNumber: 1,
    isActive: true,
  },
  {
    ruleCode: 'EMPLOYMENT_TENURE',
    ruleLabel: 'Employment History',
    category: 'INCOME',
    operator: 'GTE',
    thresholdValue: 24,
    thresholdHigh: null,
    allowedValues: null,
    factField: 'Employment_Tenure_Months__c',
    severity: 'WARNING',
    ruleExplanation: 'Employment history is less than 24 months, which may require additional verification.',
    regulatoryCitation: null,
    versionNumber: 1,
    isActive: true,
  },
  {
    ruleCode: 'ADDRESS_TENURE_MIN',
    ruleLabel: 'Address Stability',
    category: 'RESIDENCY',
    operator: 'GTE',
    thresholdValue: 12,
    thresholdHigh: null,
    allowedValues: null,
    factField: 'Address_Tenure_Months__c',
    severity: 'SOFT_DECLINE',
    ruleExplanation: 'Address history is less than 12 months at current residence.',
    regulatoryCitation: null,
    versionNumber: 1,
    isActive: true,
  },
  {
    ruleCode: 'LTV_PMI_ADVISORY',
    ruleLabel: 'PMI Advisory (LTV > 80%)',
    category: 'COLLATERAL',
    operator: 'LTE',
    thresholdValue: 0.80,
    thresholdHigh: null,
    allowedValues: null,
    factField: 'LTV_Ratio__c',
    severity: 'ADVISORY',
    ruleExplanation: 'Loan-to-value ratio exceeds 80%; private mortgage insurance (PMI) will be required.',
    regulatoryCitation: null,
    versionNumber: 1,
    isActive: true,
  },
];
