// Mock dataset — used everywhere before any real backend is wired.
// Swap these arrays for API responses later; the shapes are the contract.

import type {
  AuditCase,
  ReplayCheck,
  EvidenceItem,
  Finding,
  AuditReceipt,
  PolicyVersion,
} from "./types";

export const policyVersions: PolicyVersion[] = [
  {
    id: "POL-3.2",
    label: "Lending Policy v3.2",
    effectiveFrom: "2025-07-01",
    effectiveTo: null,
    dtiCap: 43,
    ltvCap: 80,
    minCreditScore: 620,
  },
  {
    id: "POL-3.1",
    label: "Lending Policy v3.1",
    effectiveFrom: "2024-10-01",
    effectiveTo: "2025-06-30",
    dtiCap: 45,
    ltvCap: 85,
    minCreditScore: 600,
  },
  {
    id: "POL-3.0",
    label: "Lending Policy v3.0",
    effectiveFrom: "2024-01-01",
    effectiveTo: "2024-09-30",
    dtiCap: 45,
    ltvCap: 90,
    minCreditScore: 580,
  },
];

export const auditCases: AuditCase[] = [
  {
    id: "case-001",
    loanNumber: "LN-10482",
    borrower: "Marcus Bell",
    branch: "Charlotte",
    product: "Conventional 30",
    risk: "High",
    state: "In Review",
    assignedAuditor: "S. Asheed",
    originalApprover: "M. Carter",
    approvalDate: "2025-04-18",
    policyVersionId: "POL-3.1",
    sampling: "Risk-based",
    slaStatus: "At Risk",
    dueInDays: 2,
    exceptionCount: 1,
    violationCount: 1,
  },
  {
    id: "case-002",
    loanNumber: "LN-10477",
    borrower: "Priya Nair",
    branch: "Raleigh",
    product: "FHA 30",
    risk: "Critical",
    state: "Evidence Needed",
    assignedAuditor: "S. Asheed",
    originalApprover: "D. Okonkwo",
    approvalDate: "2025-05-02",
    policyVersionId: "POL-3.1",
    sampling: "Targeted",
    slaStatus: "Overdue",
    dueInDays: -1,
    exceptionCount: 2,
    violationCount: 1,
  },
  {
    id: "case-003",
    loanNumber: "LN-10455",
    borrower: "Grant Mosely",
    branch: "Durham",
    product: "Jumbo 30",
    risk: "Critical",
    state: "In Review",
    assignedAuditor: "J. Rivera",
    originalApprover: "M. Carter",
    approvalDate: "2025-03-27",
    policyVersionId: "POL-3.1",
    sampling: "Risk-based",
    slaStatus: "On Track",
    dueInDays: 6,
    exceptionCount: 0,
    violationCount: 0,
  },
  {
    id: "case-004",
    loanNumber: "LN-10501",
    borrower: "Dolores Vance",
    branch: "Charlotte",
    product: "Conventional 15",
    risk: "Medium",
    state: "Ready for Sign-off",
    assignedAuditor: "S. Asheed",
    originalApprover: "L. Park",
    approvalDate: "2025-05-20",
    policyVersionId: "POL-3.1",
    sampling: "Random",
    slaStatus: "On Track",
    dueInDays: 9,
    exceptionCount: 1,
    violationCount: 0,
  },
  {
    id: "case-005",
    loanNumber: "LN-10460",
    borrower: "Liam Chen",
    branch: "Greensboro",
    product: "FHA 30",
    risk: "High",
    state: "Evidence Needed",
    assignedAuditor: "J. Rivera",
    originalApprover: "D. Okonkwo",
    approvalDate: "2025-02-11",
    policyVersionId: "POL-3.0",
    sampling: "Targeted",
    slaStatus: "Overdue",
    dueInDays: -3,
    exceptionCount: 1,
    violationCount: 1,
  },
  {
    id: "case-006",
    loanNumber: "LN-10512",
    borrower: "Aisha Bello",
    branch: "Raleigh",
    product: "Conventional 30",
    risk: "Medium",
    state: "In Review",
    assignedAuditor: "S. Asheed",
    originalApprover: "L. Park",
    approvalDate: "2025-05-29",
    policyVersionId: "POL-3.1",
    sampling: "Random",
    slaStatus: "On Track",
    dueInDays: 6,
    exceptionCount: 0,
    violationCount: 0,
  },
  {
    id: "case-007",
    loanNumber: "LN-10433",
    borrower: "Hank Okafor",
    branch: "Durham",
    product: "VA 30",
    risk: "Low",
    state: "Closed",
    assignedAuditor: "J. Rivera",
    originalApprover: "M. Carter",
    approvalDate: "2025-01-15",
    policyVersionId: "POL-3.0",
    sampling: "Random",
    slaStatus: "On Track",
    dueInDays: 0,
    exceptionCount: 0,
    violationCount: 0,
  },
  {
    id: "case-008",
    loanNumber: "LN-10524",
    borrower: "Owen Park",
    branch: "Charlotte",
    product: "Jumbo 30",
    risk: "High",
    state: "Ready for Sign-off",
    assignedAuditor: "S. Asheed",
    originalApprover: "D. Okonkwo",
    approvalDate: "2025-04-30",
    policyVersionId: "POL-3.1",
    sampling: "Risk-based",
    slaStatus: "At Risk",
    dueInDays: 2,
    exceptionCount: 1,
    violationCount: 0,
  },
  {
    id: "case-009",
    loanNumber: "LN-10408",
    borrower: "Renata Silva",
    branch: "Greensboro",
    product: "Conventional 30",
    risk: "Medium",
    state: "In Review",
    assignedAuditor: "J. Rivera",
    originalApprover: "L. Park",
    approvalDate: "2025-03-08",
    policyVersionId: "POL-3.1",
    sampling: "Random",
    slaStatus: "On Track",
    dueInDays: 11,
    exceptionCount: 0,
    violationCount: 0,
  },
  {
    id: "case-010",
    loanNumber: "LN-10539",
    borrower: "Tomas Reyes",
    branch: "Raleigh",
    product: "FHA 30",
    risk: "Critical",
    state: "Evidence Needed",
    assignedAuditor: "S. Asheed",
    originalApprover: "M. Carter",
    approvalDate: "2025-05-12",
    policyVersionId: "POL-3.1",
    sampling: "Targeted",
    slaStatus: "Overdue",
    dueInDays: -2,
    exceptionCount: 2,
    violationCount: 2,
  },
  {
    id: "case-011",
    loanNumber: "LN-10421",
    borrower: "Nadia Haddad",
    branch: "Durham",
    product: "Conventional 15",
    risk: "Low",
    state: "In Review",
    assignedAuditor: "J. Rivera",
    originalApprover: "L. Park",
    approvalDate: "2025-02-26",
    policyVersionId: "POL-3.0",
    sampling: "Random",
    slaStatus: "On Track",
    dueInDays: 14,
    exceptionCount: 0,
    violationCount: 0,
  },
  {
    id: "case-012",
    loanNumber: "LN-10495",
    borrower: "Felix Mwangi",
    branch: "Charlotte",
    product: "VA 30",
    risk: "Medium",
    state: "Ready for Sign-off",
    assignedAuditor: "S. Asheed",
    originalApprover: "D. Okonkwo",
    approvalDate: "2025-04-09",
    policyVersionId: "POL-3.1",
    sampling: "Risk-based",
    slaStatus: "On Track",
    dueInDays: 7,
    exceptionCount: 1,
    violationCount: 0,
  },
];

// Replay checks keyed by case. Only the interesting cases carry full sets;
// others fall back to a clean default in the API helper.
export const replayChecks: ReplayCheck[] = [
  {
    id: "chk-001-1",
    caseId: "case-001",
    rule: "DTI threshold",
    detail: "Policy cap 45% · actual 47%",
    status: "Exception",
    evidenceIds: ["ev-001-1"],
    rationaleRequired: true,
    rationale:
      "Underwriter M. Carter allowed the 2-point overage on the strength of 9 months of cash reserves.",
  },
  {
    id: "chk-001-2",
    caseId: "case-001",
    rule: "LTV limit",
    detail: "Policy cap 85% · actual 92%",
    status: "Violation",
    evidenceIds: ["ev-001-2", "ev-001-4"],
    rationaleRequired: true,
    rationale:
      "92% loan-to-value exceeds the 85% cap and no waiver was on file at approval — recorded as a violation.",
  },
  {
    id: "chk-001-3",
    caseId: "case-001",
    rule: "Income verified",
    detail: "W-2 + tax return on file",
    status: "Pass",
    evidenceIds: ["ev-001-3", "ev-001-1"],
    rationaleRequired: false,
  },
  {
    id: "chk-001-4",
    caseId: "case-001",
    rule: "Appraisal complete",
    detail: "Report present, comps thin",
    status: "Unverifiable",
    evidenceIds: ["ev-001-4"],
    rationaleRequired: true,
    rationale:
      "Appraisal is on file but the comparable sales are thin, so the value can't be independently confirmed.",
  },
  {
    id: "chk-001-5",
    caseId: "case-001",
    rule: "Exception approval",
    detail: "LTV waiver signed by M. Carter",
    status: "Violation",
    evidenceIds: ["ev-001-5"],
    rationaleRequired: true,
    rationale:
      "The waiver was signed after the loan funded, so it didn't authorize the exception at approval time.",
  },
];

export const evidenceItems: EvidenceItem[] = [
  {
    id: "ev-001-1",
    caseId: "case-001",
    label: "Form 1040 — 2024",
    kind: "Tax return",
    status: "Linked",
  },
  {
    id: "ev-001-2",
    caseId: "case-001",
    label: "Appraisal — 482 Oak St",
    kind: "Appraisal",
    status: "Mismatch",
    note: "Appraised value lower than the figure used to compute LTV.",
  },
  {
    id: "ev-001-3",
    caseId: "case-001",
    label: "W-2 — 2024",
    kind: "Income",
    status: "Linked",
  },
  {
    id: "ev-001-4",
    caseId: "case-001",
    label: "Comparable sales sheet",
    kind: "Appraisal",
    status: "Expired",
    note: "Comps older than 180 days at approval.",
  },
  {
    id: "ev-001-5",
    caseId: "case-001",
    label: "LTV exception waiver",
    kind: "Exception memo",
    status: "Contradictory",
    note: "Waiver cites a policy clause that did not exist in v3.1.",
  },
];

export const findings: Finding[] = [
  {
    id: "find-001-1",
    caseId: "case-001",
    rule: "LTV limit",
    severity: "Violation",
    summary:
      "Loan approved at 92% LTV against an 85% policy cap with no valid waiver basis.",
    guidelineRef: "Lending Policy v3.1 §4.2 — Max LTV 85% (Conventional)",
    exemptionGranted: "7-point LTV overage waived at underwriting.",
    approvedBy: "M. Carter",
    validUnderPolicy: false,
    createdBy: "S. Asheed",
    createdAt: "2026-06-12T15:20:00Z",
  },
];

export const receipts: AuditReceipt[] = [
  {
    id: "RCPT-2026-0184",
    // MOCK HASH — not a real cryptographic digest. The production sign-off
    // command will compute this from the sealed payload (SHA-256). Do not
    // present this value as tamper-evidence until that wiring lands.
    hash: "b7f3a9c1e2d4",
    caseId: "case-007",
    loanNumber: "LN-10433",
    reviewer: "J. Rivera",
    signedAt: "2026-05-30T18:04:00Z",
    policyVersionId: "POL-3.0",
    outcome: "Cleared",
    findingIds: [],
    evidenceIds: [],
    sealed: true,
    notes: [
      {
        at: "2026-06-02T09:11:00Z",
        by: "Compliance",
        text: "Reviewed in quarterly QC sample. No correction required.",
      },
    ],
  },
];
